### ISSUE TITLE
The "plaintextgen" plugin does not work with MPS 2019.1.4

### ISSUE THREAD

**Issue by danielratiu** [JetBrains/MPS-extensions#222]
"Incompatible with the current JetBrains MPS version.

![image](https://user-images.githubusercontent.com/1437141/60758973-f36ccb80-a01d-11e9-8d54-f7a89fad11a7.png)

**Comment by eugenschindler** [comment]
I don't think that the removal of the version descriptor has fixed @danielratiu's problem, because I see a screenshot of the JetBrains plugin repository browser.
Currently, plaintextgen cannot be uploaded in isolation to the plugin repository, because it has a dependency to the selection intentions plugin, but some discussions with JetBrains are ongoing on how to make all the plugins from the MPS Extensions available on the plugin repository, since it will be a nice thing for MPS to easily include the MPS Extensions "batteries", simply by installing them from the plugin repository, instead of having to download zips and loading them as libraries.

**Comment by danielratiu** [comment]
I tried locally the removing of version and that solved my problem - the plaintextgen plugin could be loaded. Thank you for the fix!
