### ISSUE TITLE
Grammar cells - optional cell does not work correctly inside of a vertical grid

### ISSUE THREAD

**Issue by hornofdavid** [JetBrains/MPS-extensions#527]
Content of optional cells is not formatted in columns when used inside of a vertical grid. This issue appeared in MPS 2021, in MPS 2020 it worked correctly.

Expected behaviour (MPS 2020):
![image](https://user-images.githubusercontent.com/90456706/176712214-37d5b83d-4f50-4262-a1e2-10029478798b.png)

Actual behaviour (MPS 2021):
![image](https://user-images.githubusercontent.com/90456706/176712291-a1a51073-e052-4291-a18b-b4d151d8409b.png)

Editor definition:
![image](https://user-images.githubusercontent.com/90456706/176712514-92b0442b-5b63-4305-b10b-0e108cace985.png)

From my testing, it seems that the issue might be caused by an additional collection (red) in the cell hierarchy:
![image](https://user-images.githubusercontent.com/90456706/176712687-f44691f1-8124-441e-8c89-1b869c1accd0.png)

**Comment by slisson** [comment]
You can just replace the optional cell with a simple "show if" condition. Doesn't look like you need the side transformations generated by the optional cell.

**Comment by alexanderpann** [comment]
@hornofdavid You are right. The optional cell itself is a collection and inside the optional cells there is another collection and therefore the grid doesn't work. However, there is a simple fix: add `grid-layout-flatten : true` from `de.itemis.mps.celllayout` to the collections inside the optional cells, and it will work again. You might also need it for nested collections inside the optional cell, so that they get flattened as well.

Let me know if you have any further issues.
