### ISSUE TITLE
Diagram Editor: view of a nested querylist editor is not updated when selecting a reference from completion menu

### ISSUE THREAD

**Issue by kbirken** [JetBrains/MPS-extensions#54]
From mbeddr.core created by [eugenschindler](https://github.com/eugenschindler) : mbeddr/mbeddr.core#1959  

When a querylist editor is nested in a diagram editor (e.g. in a diagram.box editor), upon selecting an item (e.g. a reference to some other node) from the completion menu, the name of the reference in the diagram editor is not updated visually. The update only happens when you change focus (e.g. de-focus from the cell in which you just changed the value).

Expected behavior would be that the update happens instantaneously and the superfluous focus change is not needed.

**Comment by slisson** [comment]
The issue is unrelated to querylist. The problem is that the editor that opens on double click (MPSCellEditor) references the cell it edits. After a model change the cell is replaced by a new cell that reflects that change, but the MPSCellEditor still references the old cell. We need to make sure the cell in MPSCellEditor is also replaced. Best place for this is JGraphModelSynhronizer.model2graph.

**Comment by slisson** [comment]
The update issue is fixed. It was unrelated to the querylist editor. There is a remaining issue that caret gets lost, but this because of nodes being projected at multiple locations in the same editor. This is a limitation of MPS that cannot be fixed.
