### ISSUE TITLE
WrapperCell ignores scoping constraints in used context

### ISSUE THREAD

**Issue by arimer** [JetBrains/MPS-extensions#578]
In case I am using a WrapperCell to wrap a node holding a smart reference like this:

<img width="732" alt="grafik" src="https://user-images.githubusercontent.com/16648247/215774972-553a2d8a-cb33-47e3-bcbf-1b926e8f1339.png">

All scoping constraints of the context concept ( `MyMenu`) are ignored. In my particular case I am customizing the constraints by overriding the default scope of the [ScopeProvider](http://127.0.0.1:63320/node?ref=r%3A00000000-0000-4000-0000-011c89590288%28jetbrains.mps.lang.core.structure%29%2F3734116213129792499)

**Comment by alexanderpann** [comment]
I've tested it and it is working. It has nothing to do with the WrapperCell and the constraint checking was fixed in https://github.com/JetBrains/MPS-extensions/pull/664. Are you sure that you are not confusing what the default scope is used for? When you define it in a concept A and nodes of concept A are referenced this scope is used. It is not used for the references inside concept A.

**Comment by arimer** [comment]
Thanks for checking. I don't remember that bug in detail. Therefor consider it as fixed.
